### ISSUE TITLE
Image Policy doesn't warn about missing Versioning Policy

### ISSUE THREAD

**Issue by luizbranco** [manifoldco/heighliner#113]
I have this defined:

```
apiVersion: hlnr.io/v1alpha1
kind: ImagePolicy
metadata:
  name: hlnr-test-www
  namespace: websites
spec:
  image: luizbranco/hlnr-test
  versioningPolicy:
    name: release-major
```

but no Versioning Policy matches that name. Would it be possible for the image controller to at least warning about that? Right now it's radio silent when a releases comes in.
